# Generated by Django 3.1.2 on 2021-05-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
