# Generated by Django 3.1.2 on 2021-05-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_manager', '0002_message_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='i@i.com', max_length=254),
            preserve_default=False,
        ),
    ]
