# Generated by Django 3.1.2 on 2021-05-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg_manager', '0003_message_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
    ]
