# Generated by Django 3.1.2 on 2021-05-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_manager', '0004_remove_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='q@Q.copm', max_length=254),
            preserve_default=False,
        ),
    ]
